package fr.gorisse.erp.backend.entity.default_insertion;

import fr.gorisse.erp.backend.entity.Product;
import org.springframework.stereotype.Component;

import java.util.ArrayList;

@Component
public class ProductList extends ArrayList<Product> {
    public ProductList(){
        this.add(new Product(29.99, "Un t-shirt confortable en coton", "T-shirt en coton"));
        this.add(new Product(49.99, "Un sac à dos spacieux et élégant", "Sac à dos chic"));
        this.add(new Product(9.99, "Une paire de chaussettes colorées", "Chaussettes fantaisie"));
        this.add(new Product(79.99, "Un casque audio sans fil de haute qualité", "Casque audio Bluetooth"));
        this.add(new Product(19.99, "Un livre captivant", "Livre intéressant"));
        this.add(new Product(34.99, "Un mug élégant en céramique", "Mug en céramique"));
        this.add(new Product(49.99, "Une lampe de bureau LED moderne", "Lampe LED"));
        this.add(new Product(9.99, "Un carnet de notes haut de gamme", "Carnet de notes premium"));
        this.add(new Product(59.99, "Un ensemble de cuisine en acier inoxydable", "Ensemble de cuisine élégant"));
        this.add(new Product(79.99, "Une montre-bracelet étanche", "Montre étanche"));
        this.add(new Product(29.99, "Des écouteurs intra-auriculaires sans fil", "Écouteurs Bluetooth"));
        this.add(new Product(39.99, "Un parapluie pliable et léger", "Parapluie compact"));
        this.add(new Product(129.99, "Un sac à main en cuir véritable", "Sac à main en cuir"));
        this.add(new Product(14.99, "Un ensemble de tasses à café en porcelaine", "Ensemble de tasses à café"));
        this.add(new Product(24.99, "Un roman de science-fiction best-seller", "L'Étoile lointaine"));
        this.add(new Product(14.99, "Un ensemble de tasses à expresso en porcelaine", "Ensemble de tasses à expresso"));
        this.add(new Product(39.99, "Un puzzle 1000 pièces d'une vue panoramique", "Puzzle Panoramique"));
        this.add(new Product(79.99, "Un sac à dos de randonnée résistant à l'eau", "Sac à dos Randonnée Pro"));
        this.add(new Product(49.99, "Un set de couteaux de cuisine en acier inoxydable", "Set de Couteaux Premium"));
        this.add(new Product(19.99, "Une plante d'intérieur facile d'entretien", "Plante Verte Déco"));
        this.add(new Product(69.99, "Un réveil numérique avec charge sans fil", "Réveil Intelligent"));
        this.add(new Product(29.99, "Un jeu de société stratégique pour toute la famille", "Stratégie Familiale"));
        this.add(new Product(89.99, "Une caméra de surveillance WiFi pour la maison", "Caméra de Sécurité Smart"));
        this.add(new Product(9.99, "Un porte-monnaie minimaliste en cuir", "Porte-monnaie Slim"));
        this.add(new Product(59.99, "Un ensemble de draps en coton égyptien", "Ensemble de Draps Luxe"));
        this.add(new Product(129.99, "Une cafetière automatique avec moulin intégré", "Cafetière Automatique"));
        this.add(new Product(8.99, "Un chargeur sans fil compatible avec tous les smartphones", "Chargeur sans Fil Universel"));
        this.add(new Product(49.99, "Des baskets de course légères et respirantes", "Baskets de Course AirFlow"));
        this.add(new Product(34.99, "Un tapis de yoga antidérapant et écologique", "Tapis de Yoga ÉcoPro"));
        this.add(new Product(99.99, "Un ensemble de valises rigides pour voyages", "Ensemble de Valises Voyager Plus"));
        this.add(new Product(18.99, "Un étui de protection en silicone pour AirPods", "Étui AirPods ProGuard"));
        this.add(new Product(79.99, "Un robot aspirateur intelligent avec cartographie", "Robot Aspirateur SmartClean"));
        this.add(new Product(24.99, "Un porte-bouteille isotherme pour boissons chaudes", "Porte-Bouteille Thermique"));
        this.add(new Product(159.99, "Une liseuse électronique avec écran haute résolution", "Liseuse Électronique HD"));
        this.add(new Product(29.99, "Un ensemble de pinceaux de maquillage professionnels", "Kit de Pinceaux Pro"));
        this.add(new Product(49.99, "Un support réglable pour ordinateur portable", "Support Laptop Ergo"));
        this.add(new Product(12.99, "Un diffuseur d'huiles essentielles avec éclairage LED", "Diffuseur Aromathérapie ZenLight"));
        this.add(new Product(79.99, "Un vélo d'appartement pliable avec écran LCD", "Vélo d'Appartement FoldFit"));
        this.add(new Product(39.99, "Un ensemble de verres à vin en cristal", "Ensemble de Verres Cristal Clarity"));
        this.add(new Product(149.99, "Un drone avec caméra HD et fonctions de suivi", "Drone Caméra SkyTracker"));
        this.add(new Product(69.99, "Une machine à pain automatique avec programme sans gluten", "Machine à Pain GlutenFree"));
        this.add(new Product(24.99, "Un organisateur de bureau en bois naturel", "Organisateur Bureau WoodCraft"));
        this.add(new Product(54.99, "Des enceintes Bluetooth étanches pour extérieur", "Enceintes Outdoor AquaSound"));
        this.add(new Product(8.99, "Un lot de masques faciaux lavables et réutilisables", "Masques Protection EcoSafe"));
        this.add(new Product(2.99, "Sac de riz basmati premium, 1 kg", "Riz Basmati Premium"));
        this.add(new Product(4.49, "Huile d'olive extra vierge, bouteille 500 ml", "Huile d'Olive Extra Vierge"));
        this.add(new Product(3.99, "Pâtes artisanales de blé complet, paquet 500 g", "Pâtes Complètes Artisanales"));
        this.add(new Product(1.99, "Boîte de tomates pelées de qualité, 400 g", "Tomates Pelées Qualité Premium"));
        this.add(new Product(6.99, "Miel biologique local, pot 250 g", "Miel Bio Local"));
        this.add(new Product(8.49, "Saumon fumé écossais, portion 100 g", "Saumon Fumé Écossais"));
        this.add(new Product(2.29, "Barre de chocolat noir 70%, 100 g", "Chocolat Noir Excellence"));
        this.add(new Product(4.99, "Assortiment de thés bio, boîte de 20 sachets", "Thés Bio Sélection"));
        this.add(new Product(5.49, "Fromage de chèvre frais, portion 150 g", "Fromage de Chèvre Frais"));
        this.add(new Product(3.79, "Muesli croustillant aux fruits secs, paquet 500 g", "Muesli Croustillant Fruits Secs"));
        this.add(new Product(3.99, "Sac de quinoa biologique, 500 g", "Quinoa Biologique"));
        this.add(new Product(2.49, "Bouteille de vinaigre balsamique vieilli, 250 ml", "Vinaigre Balsamique Vieilli"));
        this.add(new Product(1.79, "Paquet de biscuits au chocolat noir, 200 g", "Biscuits Chocolat Noir"));
        this.add(new Product(4.29, "Sauce tomate maison, pot 350 g", "Sauce Tomate Maison"));
        this.add(new Product(7.99, "Café moulu de commerce équitable, paquet 500 g", "Café Équitable Moulu"));
        this.add(new Product(6.49, "Filet de poulet biologique, 400 g", "Filet de Poulet Bio"));
        this.add(new Product(2.99, "Tablette de chocolat au lait, 150 g", "Chocolat au Lait Suprême"));
        this.add(new Product(5.99, "Assortiment de thés verts, boîte de 25 sachets", "Thés Verts Sélection"));
        this.add(new Product(3.29, "Fromage de brebis affiné, portion 200 g", "Fromage de Brebis Affiné"));
        this.add(new Product(4.99, "Granola aux fruits rouges, paquet 400 g", "Granola Fruits Rouges"));
        this.add(new Product(1.99, "Pâtes de blé entier biologiques, paquet 500 g", "Pâtes de Blé Entier Bio"));
        this.add(new Product(3.49, "Bouteille de huile de coco vierge, 250 ml", "Huile de Coco Vierge"));
        this.add(new Product(2.29, "Biscuits salés au parmesan, 150 g", "Biscuits Salés au Parmesan"));
        this.add(new Product(2.99, "Sauce pesto à la basilique, pot 180 g", "Sauce Pesto Basilique"));
        this.add(new Product(8.99, "Café en grains de torréfaction italienne, paquet 500 g", "Café en Grains Italiano"));
        this.add(new Product(5.49, "Truite fumée à froid, portion 120 g", "Truite Fumée à Froid"));
        this.add(new Product(3.49, "Tablette de chocolat blanc aux noix de macadamia, 100 g", "Chocolat Blanc Noix de Macadamia"));
        this.add(new Product(4.99, "Assortiment de thés noirs, boîte de 30 sachets", "Thés Noirs Sélection"));
        this.add(new Product(6.99, "Camembert fermier, portion 250 g", "Camembert Fermier"));
        this.add(new Product(4.29, "Mélange de fruits secs et noix, paquet 300 g", "Mélange Fruits Secs et Noix"));
        this.add(new Product(2.49, "Spaghetti de blé complet biologiques, paquet 500 g", "Spaghetti de Blé Complet Bio"));
        this.add(new Product(3.99, "Vinaigre de cidre de pomme biologique, bouteille 375 ml", "Vinaigre de Cidre Bio"));
        this.add(new Product(1.79, "Biscuits sans gluten aux amandes, 200 g", "Biscuits sans Gluten aux Amandes"));
        this.add(new Product(2.79, "Sauce curry douce, pot 200 g", "Sauce Curry Douce"));
        this.add(new Product(7.49, "Café moulu décaféiné, paquet 400 g", "Café Décaféiné Moulu"));
        this.add(new Product(6.99, "Saumon sauvage du Pacifique, portion 150 g", "Saumon Sauvage du Pacifique"));
        this.add(new Product(2.99, "Tablette de chocolat noir 85%, 100 g", "Chocolat Noir Intense"));
        this.add(new Product(4.49, "Thé à la menthe biologique, boîte de 20 sachets", "Thé à la Menthe Bio"));
        this.add(new Product(5.99, "Brie crémeux, portion 200 g", "Brie Crémeux"));
        this.add(new Product(3.49, "Granola à la noix de coco, paquet 350 g", "Granola Noix de Coco"));
        this.add(new Product(3.99, "Penne rigate de sarrasin sans gluten, paquet 500 g", "Penne de Sarrasin Sans Gluten"));
        this.add(new Product(4.99, "Vinaigre balsamique traditionnel de Modène, bouteille 250 ml", "Vinaigre Balsamique Traditionnel"));
        this.add(new Product(2.49, "Galettes de riz soufflé au chocolat noir, 150 g", "Galettes de Riz au Chocolat Noir"));
        this.add(new Product(2.29, "Sauce tomate aux herbes de Provence, pot 250 g", "Sauce Tomate Herbes de Provence"));
        this.add(new Product(8.99, "Café en grains bio et équitable, paquet 500 g", "Café en Grains Bio-Équitable"));
        this.add(new Product(7.49, "Filet de truite arc-en-ciel mariné au citron, portion 120 g", "Truite Marinée au Citron"));
        this.add(new Product(3.49, "Tablette de chocolat blanc à la framboise, 100 g", "Chocolat Blanc Framboise"));
        this.add(new Product(4.99, "Thé vert matcha biologique, boîte de 25 sachets", "Thé Vert Matcha Bio"));
        this.add(new Product(6.49, "Camembert au lait de chèvre, portion 180 g", "Camembert Chèvre"));
        this.add(new Product(4.29, "Muesli bio aux baies et noix, paquet 400 g", "Muesli Bio Baies et Noix"));
        this.add(new Product(2.99, "Farfalle de blé entier biologique, paquet 500 g", "Farfalle de Blé Entier Bio"));
        this.add(new Product(3.79, "Vinaigre de vin rouge vieilli, bouteille 375 ml", "Vinaigre de Vin Rouge Vieilli"));
        this.add(new Product(1.99, "Biscuits salés au fromage, 200 g", "Biscuits Salés au Fromage"));
        this.add(new Product(2.49, "Sauce barbecue fumée, pot 200 g", "Sauce Barbecue Fumée"));
        this.add(new Product(7.99, "Café moulu d'Ethiopie, paquet 400 g", "Café Moulu d'Ethiopie"));
        this.add(new Product(6.49, "Filet de saumon sauvage d'Alaska, portion 150 g", "Saumon Sauvage d'Alaska"));
        this.add(new Product(2.79, "Tablette de chocolat au lait avec noisettes, 100 g", "Chocolat au Lait Noisettes"));
        this.add(new Product(4.99, "Thé oolong de montagne, boîte de 20 sachets", "Thé Oolong de Montagne"));
        this.add(new Product(5.99, "Brie affiné au champagne, portion 200 g", "Brie Affiné au Champagne"));
        this.add(new Product(3.29, "Granola au miel et amandes, paquet 350 g", "Granola Miel et Amandes"));
        this.add(new Product(3.49, "Spaghetti de quinoa sans gluten, paquet 500 g", "Spaghetti de Quinoa Sans Gluten"));
        this.add(new Product(4.29, "Vinaigre de cidre de pomme biologique, bouteille 500 ml", "Vinaigre de Cidre Bio"));
        this.add(new Product(2.99, "Biscuits au chocolat noir et orange, 200 g", "Biscuits Chocolat Noir et Orange"));
        this.add(new Product(3.19, "Sauce curry piquante, pot 180 g", "Sauce Curry Piquante"));
        this.add(new Product(8.49, "Café en grains de Colombie, paquet 500 g", "Café en Grains Colombien"));
        this.add(new Product(7.99, "Filet de truite fumée au poivre, portion 120 g", "Truite Fumée au Poivre"));
        this.add(new Product(2.59, "Tablette de chocolat au lait praliné, 100 g", "Chocolat au Lait Praliné"));
        this.add(new Product(4.79, "Thé blanc aux fruits rouges, boîte de 25 sachets", "Thé Blanc Fruits Rouges"));
        this.add(new Product(6.79, "Fromage de chèvre affiné au thym, portion 150 g", "Chèvre Affiné au Thym"));
        this.add(new Product(3.89, "Muesli biologique aux noix de cajou, paquet 400 g", "Muesli Bio Noix de Cajou"));
    }
}
